---
abstract: 'Generate text blocks from a mixture of wrappable and protected lines'
author:
  - 'Moritz Lenz <moritz@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-BlockLayout
no_index:
  directory:
    - t
    - inc
requires:
  Moo: '0.091011'
  Test::More: '0'
  Text::Wrap: '0'
version: '0.02'
